# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Retargetly' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Retargetly
    pod 'Alamofire', '~> 4.4'

  target 'RetargetlyTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
